### PR TITLE
Fixes #11: Issue with distutils.fancy_getopt and unicode literals.

### LINKED ISSUE #11: Nose-randomly and setuptools don't get along
Trying to run `./setup.py nosetests` with the nose-randomly plugin installed causes setuptools to immediately. 

Here's the traceback:

```
% ./setup.py nosetests    
Traceback (most recent call last):
  File "./setup.py", line 304, in <module>
    test_suite='nose.collector',
  File "/usr/lib64/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 299, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib64/python2.7/distutils/dist.py", line 467, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 609, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib64/python2.7/distutils/dist.py", line 564, in _parse_command_opts
    (args, opts) = parser.getopt(args[1:])
  File "/usr/lib64/python2.7/distutils/fancy_getopt.py", line 253, in getopt
    self._grok_option_table()
  File "/usr/lib64/python2.7/distutils/fancy_getopt.py", line 171, in _grok_option_table
    "must be a string of length >= 2") % long
distutils.errors.DistutilsGetoptError: invalid long option 'with-randomly': must be a string of length >= 
2
```

My steps were:
1. `pip install nose-randomly`
2. set `test_suite='nose.collector'` in `setup()`
3. Run setup.py

### PR DESCRIPTION
**Pull request by awood**
See also https://github.com/kgrandis/nose-exclude/issues/4

### CODE REVIEW

**Comment by adamchainz** [comment]
Any way of adding a test?

**Comment by awood** [comment]
@adamchainz that test works as long as nose-randomly isn't already installed in site-packages.  If you already have it installed (like I did at one point), then the `from nose_randomly import RandomlyPlugin` at the top of the test_basic module is going to import the one from site-packages instead of the local nose_randomly module.  I'm not sure what the best way to handle that is.  Some sort of mangling of sys.path or the like?  Anyway, I wanted to get your opinion on the matter before embarking on that endeavor.

Anyhow, you can see the test pass and then make sure it fails "correctly" with this patch:

``` patch
diff --git a/nose_randomly/plugin.py b/nose_randomly/plugin.py
index 7e6db31..7e69ee7 100644
--- a/nose_randomly/plugin.py
+++ b/nose_randomly/plugin.py
@@ -30,7 +30,7 @@ else:


 class RandomlyPlugin(Plugin):
-    name = str('randomly')
+    name = 'randomly'

     def options(self, parser, env):
         """Register commandline options.
```

**Comment by awood** [comment]
I'm thinking something like http://stackoverflow.com/a/1848740/6124862 where nose_randomly is nuked from sys.modules, os.curdir is added to the front of sys.path, and then nose_randomly is imported.

**Comment by adamchainz** [comment]
I'm not keen on `sys.path` hacking or anything like that really. Btw it's only running under `tox` that's authoritative for tests, any other way of invoking them I'm not so fussed about. Since `tox` installs the package I think you could make it work by making `tox` `chdir` before running the tests so it can't pick up the local version.

**Comment by awood** [comment]
Okay, if `tox` is the authoritative source, then I won't worry about it.  Running with tox does the right thing and doesn't pick up the module under site-packages.

Let me know if there's anything else you'd like me to add.

**Comment by awood** [comment]
@adamchainz Also, I saw on your blog that you use Jekyll.  I'm going to take this opportunity to self-promote [Hawkins](https://github.com/awood/hawkins) which adds LiveReload into Jekyll.

**Comment by adamchainz** [comment]
Thx, looks useful!

**Comment by adamchainz** [comment]
Merged, and released on PyPI as 1.2.2: https://pypi.python.org/pypi/nose-randomly

**Pull request closed without merging**
